#pragma once

#define ERR_DST_INVALID -1
#define ERR_DST_INSUFFICIENT -2
#define ERR_RECORD_INVALID -3
#define ERR_RECORD_INVALID_HEADER -4
#define ERR_RECORD_INVALID_MAGIC -5
#define ERR_RECORD_SIZE_MISMATCH -6
#define ERR_RECORD_UNKNOWN -7