name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    env:
      PATH_BPF_AVAILABLE_EVENTS: "/tmp/bpf_available_events"

    steps:
    - uses: actions/checkout@v4
    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y jq llvm bpftool linux-tools-common libbpf-dev linux-headers-$(uname -r) gcc-multilib
    - name: Setup non-sudo build
      run: |
        sudo cat /sys/kernel/tracing/available_events > "${PATH_BPF_AVAILABLE_EVENTS}"
        sudo chmod a+r "${PATH_BPF_AVAILABLE_EVENTS}"
    - name: configure
      run: ./configure CC=clang --prefix="${PWD}/local-install" --with-path-tracing-available-events="${PATH_BPF_AVAILABLE_EVENTS}"
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
